name: Lint

on:
  - push

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 14

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run ESLint
        run: yarn lint
